kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rbtask3ken
  namespace: dev
subjects:
  - kind: ServiceAccount
    name: ken
    namespace: dev
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io